apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ledukeg97-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ledukeg97-go 
  name: ledukeg97-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ledukeg97-go 
